// <auto-generated />
namespace Bodytech.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class entidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241306006_entidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
