// <auto-generated />
namespace Bodytech.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rl_role_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rl_role_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250028029_rl_role_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
